displayName=Banked Item Usage
author=Aaron Rader
description=Highlights items based on last deposit/withdrawal date
tags=bank,gear
version=
plugins=com.bankeditemusage.BankedItemUsagePlugin
build=standard